---
# defaults file for system_config

# system_config_flatpak_packages:
#   - com.jgraph.drawio.desktop
#   - com.mattjakeman.ExtensionManager
#   - com.slack.Slack
#   - im.riot.Riot
#   - io.podman_desktop.PodmanDesktop
#   # - org.flameshot.Flameshot
#   # - org.gnome.DejaDup
#   - org.shotcut.Shotcut
#   - org.pgadmin.pgAdmin4
#   - org.videolan.VLC
#   - us.zoom.Zoom

system_config_flatpak_packages: []

# system_config_rpmfusion: none | free | nonfree | both
system_config_rpmfusion: "none"

# system_config_dnf_repositories:
#   - name: example-repo
#     description: Example Repository
#     baseurl: https://example.com/repo/$releasever/$basearch
#     gpgcheck: true
#     gpgkey: https://example.com/RPM-GPG-KEY-example

system_config_dnf_repositories: []

# system_config_copr_repositories:
#   - name: user/project

system_config_copr_repositories: []

# system_config_packages:
#   - vim-enhanced
#   - htop
#   - tmux

system_config_packages: []

# system_config_v4l2loopback: true
system_config_v4l2loopback: false
system_config_v4l2loopback_devices: 1
system_config_v4l2loopback_video_nr: 20
system_config_v4l2loopback_card_label: "VirtualCam"
system_config_v4l2loopback_max_buffers: 2
system_config_v4l2loopback_exclusive_caps: 1
