---
- name: aws_cli | Apply default install_cloud_clis_aws_install_root when not set by caller
  ansible.builtin.set_fact:
    install_cloud_clis_aws_install_root: "{{ ansible_facts['user_dir'] }}/.local/aws-cli"
  when: install_cloud_clis_aws_install_root is not defined

- name: aws_cli | Check if AWS CLI binary installed
  ansible.builtin.stat:
    path: "{{ install_cloud_clis_bin_dir }}/aws"
  register: __install_cloud_clis_aws_cli_installed

- name: aws_cli | Check AWS CLI versions (Block)
  when: __install_cloud_clis_aws_cli_installed.stat.exists
  block:
    - name: aws_cli | Retrieve AWS CLI versions
      ansible.builtin.uri:
        url: https://api.github.com/repos/aws/aws-cli/tags
      register: __install_cloud_clis_aws_cli_versions

    - name: aws_cli | Determine latest AWS CLI version
      ansible.builtin.set_fact:
        __install_cloud_clis_latest_aws_cli_ver: "{{ __install_cloud_clis_aws_cli_versions.json[0]['name'] }}"

    - name: aws_cli | Retrieve installed AWS CLI version
      ansible.builtin.command:
        cmd: aws --version
      register: __install_cloud_clis_aws_ver_installed_result
      changed_when: false

    - name: aws_cli | Determine installed AWS CLI version
      ansible.builtin.set_fact:
        __install_cloud_clis_installed_aws_cli_ver: "{{ __install_cloud_clis_aws_ver_installed_result.stdout | regex_replace('^aws-cli/([0-9.]+).*$', '\\1') }}"

- name: aws_cli | Display AWS CLI version info
  ansible.builtin.debug:
    msg: |
      [
        "Installed Version: {{ __install_cloud_clis_installed_aws_cli_ver | default('NOT INSTALLED') }}",
        "Latest Version:    {{ __install_cloud_clis_latest_aws_cli_ver }}",
      ]
    verbosity: 1

- name: aws_cli | Update AWS CLI (Block)
  when: (not __install_cloud_clis_aws_cli_installed.stat.exists) or (__install_cloud_clis_installed_aws_cli_ver != __install_cloud_clis_latest_aws_cli_ver)
  block:
    - name: aws_cli | Create temporary directory
      ansible.builtin.tempfile:
        state: directory
      register: __install_cloud_clis_aws_temp_dir

    # See https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html
    - name: aws_cli | Unzip the AWS CLI installer
      ansible.builtin.unarchive:
        src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: "{{ __install_cloud_clis_aws_temp_dir['path'] }}"
        remote_src: true

    - name: aws_cli | Update AWS CLI
      ansible.builtin.command:
        cmd: ./aws/install -i {{ install_cloud_clis_aws_install_root }} -b {{ install_cloud_clis_bin_dir }} --update
        chdir: "{{ __install_cloud_clis_aws_temp_dir['path'] }}"
      changed_when: true

    - name: aws_cli | Remove temporary directory
      when: __install_cloud_clis_aws_temp_dir['path'] is defined
      ansible.builtin.file:
        path: "{{ __install_cloud_clis_aws_temp_dir['path'] }}"
        state: absent

    - name: aws_cli | Add updated message
      when: (__install_cloud_clis_installed_aws_cli_ver is defined) and (__install_cloud_clis_installed_aws_cli_ver != __install_cloud_clis_latest_aws_cli_ver)
      ansible.builtin.set_fact:
        install_cloud_clis_update_messages: >
          {{ install_cloud_clis_update_messages + ["Updated AWS CLI from " + __install_cloud_clis_installed_aws_cli_ver + " to " + __install_cloud_clis_latest_aws_cli_ver] }}

    - name: aws_cli | Add installed message
      when: not __install_cloud_clis_aws_cli_installed.stat.exists
      ansible.builtin.set_fact:
        install_cloud_clis_update_messages: >
          {{ install_cloud_clis_update_messages + ["Installed AWS CLI"] }}

- name: aws_cli | Find old major versions to cleanup
  ansible.builtin.find:
    paths:
      - "{{ install_cloud_clis_aws_install_root }}"
    file_type: directory
    recurse: false
  register: __install_cloud_clis_aws_cli_major_version_dirs_result

- name: aws_cli | Create major version directory list
  ansible.builtin.set_fact:
    __install_cloud_clis_aws_cli_major_version_dirs: "{{ __install_cloud_clis_aws_cli_major_version_dirs | default([]) + [__install_cloud_clis_aws_cli_mvd['path']] }}"
  loop: "{{ __install_cloud_clis_aws_cli_major_version_dirs_result['files'] }}"
  loop_control:
    loop_var: __install_cloud_clis_aws_cli_mvd
    label: "Adding {{ __install_cloud_clis_aws_cli_mvd['path'] }}"

- name: aws_cli | Default major version directory list when empty
  when: __install_cloud_clis_aws_cli_major_version_dirs is not defined
  ansible.builtin.set_fact:
    __install_cloud_clis_aws_cli_major_version_dirs: []

- name: aws_cli | Find versions to remove
  when: __install_cloud_clis_aws_cli_major_version_dirs | length > 0
  ansible.builtin.find:
    paths: "{{ __install_cloud_clis_aws_cli_major_version_dirs }}"
    file_type: directory
    recurse: false
    excludes:
      - "{{ __install_cloud_clis_latest_aws_cli_ver }}"
      - "{{ __install_cloud_clis_installed_aws_cli_ver }}"
  register: __install_cloud_clis_aws_cli_vers_to_del_result

- name: aws_cli | Remove old versions that were found
  when: __install_cloud_clis_aws_cli_vers_to_del_result is defined
  ansible.builtin.file:
    path: "{{ __install_cloud_clis_aws_cli_ver_to_del['path'] }}"
    state: absent
  loop: "{{ __install_cloud_clis_aws_cli_vers_to_del_result['files'] }}"
  loop_control:
    loop_var: __install_cloud_clis_aws_cli_ver_to_del
    label: "Removing {{ __install_cloud_clis_aws_cli_ver_to_del['path'] }}"

- name: aws_cli | Add aws command-line completion to .bashrc
  ansible.builtin.lineinfile:
    path: "{{ ansible_facts['user_dir'] }}/.bashrc"
    regexp: complete -C .* aws
    line: command -v aws &>/dev/null && complete -C '{{ install_cloud_clis_bin_dir }}/aws_completer' aws
