---
- name: Ensure user home directory fact is available
  when: "'user_dir' not in ansible_facts"
  ansible.builtin.setup:
    gather_subset:
      - "!all"
      - min

- name: Update CLIs (Block)
  block:
    - name: Install AWS CLI
      when: "'aws' in install_cloud_clis_components"
      ansible.builtin.include_tasks:
        file: aws_cli.yml

    - name: Install OC CLI
      when: "'oc' in install_cloud_clis_components"
      ansible.builtin.include_tasks:
        file: oc_cli.yml

    - name: Install ROSA CLI
      when: "'rosa' in install_cloud_clis_components"
      ansible.builtin.include_tasks:
        file: rosa_cli.yml

    - name: Install Tekton CLI
      when: "'tekton' in install_cloud_clis_components"
      ansible.builtin.include_tasks:
        file: tekton_cli.yml

    - name: Install kube-linter
      when: "'kube_linter' in install_cloud_clis_components"
      ansible.builtin.include_tasks:
        file: kube-linter.yml

    - name: Install kustomize
      when: "'kustomize' in install_cloud_clis_components"
      ansible.builtin.include_tasks:
        file: kustomize.yml

    - name: Install stern
      when: "'stern' in install_cloud_clis_components"
      ansible.builtin.include_tasks:
        file: stern.yml

    - name: Install helm
      when: "'helm' in install_cloud_clis_components"
      ansible.builtin.include_tasks:
        file: helm.yml

  always:
    - name: Display upgrade results
      ansible.builtin.debug:
        msg: "{{ (install_cloud_clis_update_messages | length > 0) | ternary(install_cloud_clis_update_messages, 'All CLIs are already at the latest version') }}"
