---
- name: Gather minimal facts
  ansible.builtin.setup:
    gather_subset:
      - "!all"
      - min

- name: Apply default install_cloud_clis_bin_dir when not set by caller
  ansible.builtin.set_fact:
    install_cloud_clis_bin_dir: "{{ ansible_facts['user_dir'] }}/.local/bin"
  when: install_cloud_clis_bin_dir is not defined

- name: Ensure install_cloud_clis_bin_dir exists
  ansible.builtin.file:
    path: "{{ install_cloud_clis_bin_dir }}"
    state: directory
    mode: "0755"

- name: Update CLIs (Block)
  block:
    - name: Install CLI components
      ansible.builtin.include_tasks:
        file: install_cli_component.yml
      loop: "{{ install_cloud_clis_cli_installers | selectattr('component', 'in', install_cloud_clis_components) | list }}"
      loop_control:
        loop_var: install_cloud_clis_cli
        label: "{{ install_cloud_clis_cli.label }}"

  always:
    - name: Refresh .bashrc completion block
      when: install_cloud_clis_manage_bashrc_completion | bool
      ansible.builtin.include_tasks:
        file: bashrc_completion.yml

    - name: Display upgrade results
      ansible.builtin.debug:
        msg: "{{ (install_cloud_clis_update_messages | length > 0) | ternary(install_cloud_clis_update_messages, 'All CLIs are already at the latest version') }}"
