---
- name: oc_cli | Retrieve latest OC CLI release info
  ansible.builtin.uri:
    url: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/release.txt
    return_content: true
  register: __install_cloud_clis_oc_cli_release_info

- name: oc_cli | Determine latest OC CLI version
  ansible.builtin.set_fact:
    __install_cloud_clis_latest_oc_cli_ver: "{{ __install_cloud_clis_oc_cli_release_info['content'] | regex_replace('(?s).*^Release Metadata:\\s+Version:\\s+(?P<version>[0-9.]+).*$', '\\g<version>', multiline=True) }}"

- name: oc_cli | Check if OC CLI binary installed
  ansible.builtin.stat:
    path: "{{ install_cloud_clis_bin_dir }}/oc"
  register: __install_cloud_clis_oc_cli_installed

- name: oc_cli | Check OC CLI versions (Block)
  when: __install_cloud_clis_oc_cli_installed.stat.exists
  block:
    - name: oc_cli | Retrieve installed OC CLI version
      ansible.builtin.command:
        cmd: oc version --client -o json
      register: __install_cloud_clis_oc_ver_installed_result
      changed_when: false

    - name: oc_cli | Determine installed OC CLI version
      ansible.builtin.set_fact:
        __install_cloud_clis_installed_oc_cli_ver: "{{ (__install_cloud_clis_oc_ver_installed_result.stdout | from_json)['releaseClientVersion'] }}"

- name: oc_cli | Display OC CLI version info
  ansible.builtin.debug:
    msg: |
      [
        "Installed Version: {{ __install_cloud_clis_installed_oc_cli_ver | default('NOT INSTALLED') }}",
        "Latest Version:    {{ __install_cloud_clis_latest_oc_cli_ver }}",
      ]
    verbosity: 1

- name: oc_cli | Update OC CLI executable (Block)
  when: (not __install_cloud_clis_oc_cli_installed.stat.exists) or (__install_cloud_clis_installed_oc_cli_ver != __install_cloud_clis_latest_oc_cli_ver)
  block:
    - name: oc_cli | Update OC CLI executable
      ansible.builtin.unarchive:
        src: https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/latest/openshift-client-linux.tar.gz
        dest: "{{ install_cloud_clis_bin_dir }}"
        remote_src: true
        include:
          - "oc"
          - "kubectl"

    - name: oc_cli | Add updated message
      when: (__install_cloud_clis_installed_oc_cli_ver is defined) and (__install_cloud_clis_installed_oc_cli_ver != __install_cloud_clis_latest_oc_cli_ver)
      ansible.builtin.set_fact:
        install_cloud_clis_update_messages: >
          {{ install_cloud_clis_update_messages + ["Updated OC CLI from " + __install_cloud_clis_installed_oc_cli_ver + " to " + __install_cloud_clis_latest_oc_cli_ver] }}

    - name: oc_cli | Add installed message
      when: not __install_cloud_clis_oc_cli_installed.stat.exists
      ansible.builtin.set_fact:
        install_cloud_clis_update_messages: >
          {{ install_cloud_clis_update_messages + ["Installed OC CLI"] }}

- name: oc_cli | Add oc command-line completion to .bashrc
  ansible.builtin.lineinfile:
    path: "{{ ansible_facts['user_dir'] }}/.bashrc"
    regexp: source <\(oc completion bash\)
    line: command -v oc &>/dev/null && source <(oc completion bash)
