---
- name: stern | Retrieve stern CLI versions
  ansible.builtin.uri:
    url: https://api.github.com/repos/stern/stern/releases
  register: __install_cloud_clis_stern_cli_versions

- name: stern | Determine latest stern GA release version details
  ansible.builtin.set_fact:
    __install_cloud_clis_latest_stern_cli_ver_details: >-
      {{ __install_cloud_clis_stern_cli_versions.json |
         selectattr('prerelease', 'equalto', false) |
         first
      }}

- name: stern | Determine latest stern version
  ansible.builtin.set_fact:
    __install_cloud_clis_latest_stern_cli_ver: >-
      {{ __install_cloud_clis_latest_stern_cli_ver_details['tag_name'] |
         regex_replace('^v(?P<version>[0-9.]+)$', '\g<version>')
      }}

- name: stern | Determine latest stern download URL
  ansible.builtin.set_fact:
    __install_cloud_clis_latest_stern_cli_url: >-
      {{ __install_cloud_clis_latest_stern_cli_ver_details['assets'] |
         selectattr('name', 'contains', 'linux_amd64') |
         map(attribute='browser_download_url') |
         first
      }}

- name: stern | Check if stern binary installed
  ansible.builtin.stat:
    path: "{{ install_cloud_clis_bin_dir }}/stern"
  register: __install_cloud_clis_stern_cli_installed

- name: stern | Check stern versions (Block)
  when: __install_cloud_clis_stern_cli_installed.stat.exists
  block:
    - name: stern | Retrieve installed stern version
      ansible.builtin.command:
        cmd: stern --version
      register: __install_cloud_clis_stern_ver_installed_result
      changed_when: false

    - name: stern | Determine installed stern version
      ansible.builtin.set_fact:
        __install_cloud_clis_installed_stern_cli_ver: >-
          {{ __install_cloud_clis_stern_ver_installed_result.stdout |
             regex_replace('(?s)^version: (?P<version>[0-9.]+).*$', '\g<version>')
          }}

- name: stern | Display stern version info
  ansible.builtin.debug:
    msg: |
      [
        "Installed Version: {{ __install_cloud_clis_installed_stern_cli_ver | default('NOT INSTALLED') }}",
        "Latest Version:    {{ __install_cloud_clis_latest_stern_cli_ver }}",
        "URL for latest version: {{ __install_cloud_clis_latest_stern_cli_url }}"
      ]
    verbosity: 1

- name: stern | Update stern executable (Block)
  when: (not __install_cloud_clis_stern_cli_installed.stat.exists) or (__install_cloud_clis_installed_stern_cli_ver != __install_cloud_clis_latest_stern_cli_ver)
  block:
    - name: stern | Update stern executable
      ansible.builtin.unarchive:
        src: "{{ __install_cloud_clis_latest_stern_cli_url }}"
        dest: "{{ install_cloud_clis_bin_dir }}"
        remote_src: true
        include:
          - "stern"

    - name: stern | Add updated message
      when: (__install_cloud_clis_installed_stern_cli_ver is defined) and (__install_cloud_clis_installed_stern_cli_ver != __install_cloud_clis_latest_stern_cli_ver)
      ansible.builtin.set_fact:
        install_cloud_clis_update_messages: >
          {{ install_cloud_clis_update_messages + ["Updated stern from " + __install_cloud_clis_installed_stern_cli_ver + " to " + __install_cloud_clis_latest_stern_cli_ver] }}

    - name: stern | Add installed message
      when: not __install_cloud_clis_stern_cli_installed.stat.exists
      ansible.builtin.set_fact:
        install_cloud_clis_update_messages: >
          {{ install_cloud_clis_update_messages + ["Installed stern"] }}

- name: stern | Add stern command-line completion to .bashrc
  ansible.builtin.lineinfile:
    path: "{{ ansible_facts['user_dir'] }}/.bashrc"
    line: source <(stern --completion=bash)
