---
galaxy_info:
  author: Brant Evans
  description: Fedora Linux system-wide configuration (repos, packages, users, Flatpak).
  license: GPL-3.0-only
  min_ansible_version: "2.16"
  galaxy_tags: []

dependencies: []
