---
- name: Dconf | Apply dconf settings
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value | default(omit) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ user_config_dconf_settings }}"
  loop_control:
    label: "{{ item.key }}"
