---
- name: Flatpak | Ensure per-user flatpak overrides directory exists
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/.local/share/flatpak/overrides"
    state: directory
    mode: "0755"
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_gid'] }}"

- name: Flatpak | Create configuration file to set Slack flatpak permissions
  ansible.builtin.template:
    src: com.slack.Slack.overrides.j2
    dest: "{{ ansible_facts['user_dir'] }}/.local/share/flatpak/overrides/com.slack.Slack"
    mode: "0644"
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_gid'] }}"
