---
# tasks file for user_config

- name: Gather minimal facts
  ansible.builtin.setup:
    gather_subset:
      - "!all"
      - min

- name: Include DConf tasks
  ansible.builtin.include_tasks:
    file: dconf.yml
  when: user_config_dconf_settings | length > 0

- name: Include Flatpak tasks
  ansible.builtin.include_tasks:
    file: flatpak.yml

- name: Include GTK tasks
  ansible.builtin.include_tasks:
    file: gtk.yml

- name: Include GNOME Shell extension tasks
  ansible.builtin.include_tasks:
    file: gnome_extensions.yml
  when: user_config_gnome_extensions | length > 0
