---
galaxy_info:
  author: Brant Evans
  description: Install or upgrade OpenShift Local (CRC) for the connection user.
  license: GPL-3.0-only
  min_ansible_version: "2.16"
  galaxy_tags: []

dependencies: []
