---
galaxy_info:
  author: Brant Evans
  description: Per-user configuration preferences for the Ansible connection user.
  license: GPL-3.0-only
  min_ansible_version: "2.16"
  galaxy_tags: []

dependencies: []
